/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CardHeaderFooter: typeof import('./resources/js/components/shared/CardHeaderFooter.vue')['default']
    CardStatisticsHorizontal: typeof import('./resources/js/@core/components/cards/CardStatisticsHorizontal.vue')['default']
    CardStatisticsVertical: typeof import('./resources/js/@core/components/cards/CardStatisticsVertical.vue')['default']
    CardStatisticsWithImages: typeof import('./resources/js/@core/components/cards/CardStatisticsWithImages.vue')['default']
    DefaultText: typeof import('./resources/js/components/style-components/typography/DefaultText.vue')['default']
    ErrorHeader: typeof import('./resources/js/@core/components/ErrorHeader.vue')['default']
    Heading: typeof import('./resources/js/components/style-components/typography/Heading.vue')['default']
    LoginForm: typeof import('./resources/js/components/auth/LoginForm.vue')['default']
    MonthlyEarnings: typeof import('./resources/js/components/dashboard/MonthlyEarnings.vue')['default']
    MoreBtn: typeof import('./resources/js/@core/components/MoreBtn.vue')['default']
    ProductCards: typeof import('./resources/js/components/dashboard/ProductCards.vue')['default']
    ProductPerformance: typeof import('./resources/js/components/dashboard/ProductPerformance.vue')['default']
    RecentTransaction: typeof import('./resources/js/components/dashboard/RecentTransaction.vue')['default']
    RegisterForm: typeof import('./resources/js/components/auth/RegisterForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Salesoverview: typeof import('./resources/js/components/Salesoverview.vue')['default']
    SalesOverview: typeof import('./resources/js/components/dashboard/SalesOverview.vue')['default']
    Shadow: typeof import('./resources/js/components/style-components/shadow/Shadow.vue')['default']
    ThemeSwitcher: typeof import('./resources/js/@core/components/ThemeSwitcher.vue')['default']
    UiChildCard: typeof import('./resources/js/components/shared/UiChildCard.vue')['default']
    UiParentCard: typeof import('./resources/js/components/shared/UiParentCard.vue')['default']
    UiTableCard: typeof import('./resources/js/components/shared/UiTableCard.vue')['default']
    UiTextfieldPrimary: typeof import('./resources/js/components/shared/UiTextfieldPrimary.vue')['default']
    WidgetCard: typeof import('./resources/js/components/shared/WidgetCard.vue')['default']
    WidgetCardv2: typeof import('./resources/js/components/shared/WidgetCardv2.vue')['default']
    YearlyBreakup: typeof import('./resources/js/components/dashboard/YearlyBreakup.vue')['default']
  }
}
